### ISSUE TITLE
Unable to implement usabilla in iOS

### ISSUE THREAD

**Issue by mink-ang** [usabilla/usabilla-u4a-react-native#82]
Xcode version: 1.11
Usabilla React Native version: 0.8.3 (with iOS SDK v6.4.2)
React Native version: 0.60.5

Steps to reproduce error
1. Create a new project by react-native init <PROJECT_NAME> --version 0.60.5
2. Follow usabilla documentation to install usabilla-react-native 
- yarn add usabilla-react-native
- react-native link usabilla-react-native
- created bridging header file
- added framework search path
- created a New Copy Files Phase and dragged Usabilla framework from node_modules/usabilla-react-native/ios/Usabilla.framework (because the path 'ReactNativeUsabilla/Frameworks ' doesn't exist)
- Added camera and photo privacy into info.plist
- Bulld project in Xcode

Error 1: 'React/RCTBridgeModule.h' file not found
Suspect: React Native 0.60 and above does not come with React.xcodeproj anymore but usabilla library is still referencing it.

Error 2: module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler
Double checked that I am using usabilla-react-native v0.8.3 which has the latest iOS SDK from Usabilla (v6.4.2). Also tried this 
[https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler](https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler)
 Still couldn't get it to work.

**Comment by torkvell** [comment]
Hi @mink-ang ,

I'm sorry to hear you're running into issues with buiding your React Native app. This happens due to a difference in the compiler versions. Our latest iOS SDK was built with Swift 5.1. Your Xcode version are using the 5.1.2 compiler. We will release a new iOS SDK early next week. You can then include the framework file from the iOS repo and replace it with your local version. This is outlined in this ticket: [https://github.com/usabilla/usabilla-u4a-react-native/issues/75](https://github.com/usabilla/usabilla-u4a-react-native/issues/75)

I hope this helps for now. Please let me know if there is anything else I can assist on.

**Comment by torkvell** [comment]
Hi @mink-ang ,

We've now released iOS version 6.4.3 with module format stability. This should resolve issues with compiler issues from Xcode 11 and forward. You can now include the framework file from the iOS repo and replace it with your local version. How to do this is outlined in this ticket: [#75](https://github.com/usabilla/usabilla-u4a-react-native/issues/75)

If there is anything else, please let us know.

**Comment by quyentran-agilityio** [comment]
Is it work for now @mink-ang ? I got the same issues.
After install latest version of usabilla-react-native (0.8.4) (sdk version 6.4.3) fixed Error 2: module compiled with Swift 5.1 but did not fixed Error 1: 'React/RCTBridgeModule.h' file not found. 
@torkvell

**Comment by classyklaas** [comment]
@quyentran-agilityio 

Thank you for contacting Usabilla! We're happy to help. Before deep-diving into a specific solution/advise from our end, I'd first like to quickly discuss two specific points.

- Could you please confirm your version of React Native? So, not the version of our React Native bridge, but the version of React Native you created your app with. 

- Also, could you please confirm you've followed the exact steps as outlined in our readme-file? Below, you'll find the exact link to this file:

https://github.com/usabilla/usabilla-u4a-react-native/blob/master/README.md

**Comment by quyentran-agilityio** [comment]
@classyklaas , Thanks for replied.

- I am using react-native 0.60.5 for my custom app
- I followed exact steps as outlined in README

**Comment by classyklaas** [comment]
Hi @quyentran-agilityio, thank you for your reply. Good to know.

Could you please try the following?

- In Xcode, go to the project scheme (Product -> Scheme -> Manage Scheme -> double-click on your project).
- Click on the option called 'Buil'd on the left pane.
- Uncheck 'Parallelize Build' under Build Options.
- Then in Targets section, click '+' button then search for 'React'. Select it and click 'Add'.
'React' should now appear under Targets section. Click and drag it to the top so that it will be the first item in the list (before your project).
- Clean the project and build.

If 'React' isn't shown there, then please go to the the following folder:  
`YourProject ▸ ⁨node_modules⁩ ▸ ⁨react-native⁩ ▸ ⁨React⁩ ▸ React.xcodeproj`

- Drag this project to the root of your project in Xcode.

If this doesn't help, it might be better to contact us directly via support@usabilla.com with as much additional information as possible.

**Comment by mink-ang** [comment]
@quyentran-agilityio The: `'React/RCTBridgeModule.h' file not found` error is due to react missing as a dependency. I have a fork that addressed that problem. @classyklaas I have created a PR, can you please review and merge before the next release?

**Comment by torkvell** [comment]
@mink-ang ,

Thank you for your PR request. However, we will wait for our next React Native update which will support the auto-linking feature. This shall resolve compiler versioning issues. The next release date will be in approximately 10 days.

**Comment by torkvell** [comment]
For all others who might run into any of this. Try this:

1. In Xcode, go to the project scheme (Product -> Scheme -> Manage Scheme -> double click your project).
2. Click on the 'Build' option at the left pane.
3. Uncheck 'Parallelize Build' under Build Options.
4. Then in Targets section, click '+' button then search for 'React'. Select it and click 'Add'.
'React' should now appear under Targets section. Click and drag it to the top so that it will be the first item in the list (before your project).
5. Clean the project and build.

if 'React' doesn't appear or is missing then go to the folder  
`YourProject ▸ ⁨node_modules⁩ ▸ ⁨react-native⁩ ▸ ⁨React⁩ ▸ React.xcodeproj`
--> Drag this project to the root of your project in Xcode.

**Comment by keshcreations** [comment]
Hi @mink-ang & @quyentran-agilityio,

Our team released a new version of our React Native SDK with auto-linking. I would like to invite you to have a look at it and try it out. Installing this version of the SDK is different from the previous versions hence why we updated our documentation as well.

Feel free to share any feedback you might have with us.
